### ISSUE TITLE
Merge has caused bookView and updating of window focus type to be lost.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/m2#459]
Some calls were replaced with event emissions, and the parent is calling the children's methods. Sometimes clicking on the thumbnail strip no longer updates the canvas.

**Comment by rsinghal** [comment]
Darn, I thought I reverted that before I pushed.  Will fix.

**Comment by aeschylus** [comment]
Still getting the behaviour in master. Just to make sure we mean the same thing:
![screen shot 2015-03-13 at 11 13 19](https://cloud.githubusercontent.com/assets/145874/6644538/0cc5459e-c972-11e4-9223-4794fb205a15.png)

**Comment by rsinghal** [comment]
This seems to be for #458

**Comment by aeschylus** [comment]
Whoops, yep. Sorry.
